# 1.1 수학과 파이썬 복습
## 1.1.1 벡터와 행렬

In [2]:
import numpy as np
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [3]:

x = np.array([1,2,3])
x.__class__
x.shape
x.ndim

W = np.array([[1,2,3],[4,5,6]])
W.shape
W.ndim

numpy.ndarray

(3,)

1

(2, 3)

2

## 1.1.2 행렬의 원소별 연산

In [4]:
W = np.array([[1,2,3],[4,5,6]])
X = np.array([[0,1,2],[3,4,5]])
W+X
W*X

array([[ 1,  3,  5],
       [ 7,  9, 11]])

array([[ 0,  2,  6],
       [12, 20, 30]])

## 1.1.3 브로드캐스트

In [5]:
A = np.array([[1,2],[3,4]])
A * 10

array([[10, 20],
       [30, 40]])

In [6]:
A = np.array([[1,2],[3,4]])
b = np.array([[10,20]])
A*b

array([[10, 40],
       [30, 80]])

## 1.1.4 벡터의 내적과 행렬의 곱

In [7]:
# 벡터의 내적
a = np.array([1,2,3])
b = np.array([4,5,6])
np.dot(a,b)

#행렬의 곱
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
np.matmul(A, B)


np.int64(32)

array([[19, 22],
       [43, 50]])

# 1.2 신경망의 추론
### 1.2.1 신경망 추론 전체 그림

In [15]:
import numpy as np


def sigmoid(x):
    return 1 / (1 + np.exp(-x))

x = np.random.randn(10, 2) #입력
x
W1 = np.random.randn(2, 4) # 가중치
b1 = np.random.randn(4) # 편향
W2 = np.random.randn(4,3)
b2 = np.random.randn(3)


h = np.matmul(x, W1) + b1
a = sigmoid(h)
s = np.matmul(a, W2) + b2

h
a
s

array([[-0.34454992, -0.08752482],
       [-0.41396789,  0.01655693],
       [-1.25494912,  0.12923967],
       [-0.27466902,  1.53946173],
       [-2.61186959, -0.01279258],
       [ 0.96451687,  0.45274126],
       [ 1.02374848,  1.00944191],
       [ 1.04073107, -0.44538184],
       [-0.97612656, -0.62813495],
       [ 1.15053158, -1.93678549]])

array([[-0.42126826,  0.11655201,  0.54717247, -1.78580186],
       [-0.62603312,  0.07305534,  0.5268574 , -2.06627231],
       [-1.24109698,  0.09146197,  0.99604645, -3.26503261],
       [-3.02882728, -0.66216251, -0.51118442, -4.82006703],
       [-1.70733098,  0.27497154,  1.95482213, -4.57901178],
       [-0.62664736, -0.25200618, -0.62899216, -1.29043738],
       [-1.50072429, -0.52147719, -1.0137805 , -2.28737844],
       [ 0.87173105,  0.1680395 , -0.11838519,  0.51869469],
       [ 0.13267232,  0.42733091,  1.28902553, -1.4886443 ],
       [ 3.35129703,  0.86699152,  0.74026652,  3.5033116 ]])

array([[0.39621331, 0.52910506, 0.63347933, 0.1435882 ],
       [0.34841056, 0.51825572, 0.62874985, 0.11241845],
       [0.2242451 , 0.52284957, 0.73028055, 0.03679045],
       [0.04614041, 0.340254  , 0.37491591, 0.0080017 ],
       [0.15351022, 0.568313  , 0.87597149, 0.01016074],
       [0.34827113, 0.43732977, 0.3477391 , 0.21577879],
       [0.18231752, 0.37250688, 0.26624065, 0.09217368],
       [0.70510577, 0.5419113 , 0.47043822, 0.62684249],
       [0.53311951, 0.60523614, 0.7839822 , 0.1841253 ],
       [0.96614728, 0.70411931, 0.67705413, 0.97078185]])

array([[ 1.61327807, -0.3753685 , -0.53683058],
       [ 1.58732851, -0.31629168, -0.58590113],
       [ 1.67137528, -0.17518603, -0.78947441],
       [ 1.13766837,  0.23387904, -0.54102264],
       [ 1.82011593, -0.12514434, -0.95994395],
       [ 1.18852678, -0.19995999, -0.21094748],
       [ 1.02090076,  0.01745129, -0.35013767],
       [ 1.46266724, -0.51963778,  0.37807358],
       [ 1.877272  , -0.60952662, -0.58139285],
       [ 1.77089033, -0.82706303,  0.74529553]])

## 1.2.2 계층으로 클래스화 및 순전파 구현

In [ ]:
import numpy as np

class Sigmoid:
    def __init__(self):
        self.params = []

    def forward(self, x):
        return 1 / (1 + np.exp(-x))
    
class Affine:
    def __init__(self, W, b):
        self.params = [W, b]
    
    def forward(self, x):
        W, b = self.params
        out = np.matmul(x, W) + B
        return out
    